### ISSUE TITLE
[Libretro] (Chrono Trigger) Screen Flashes Briefly When Battles Begin

### ISSUE THREAD

**Issue by Awakened0** [SourMesen/Mesen-S#102]
There is a quick white flash at the start of battles in CT that only happens in the libretro build. The screen also seems to shift down a pixel for the second it flashes. There was a [similar issue with the snes9x core awhile back](https://github.com/libretro/libretro-meta/issues/83). But unlike that issue, it's happening even without any overscan cropping.

**Comment by SourMesen** [comment]
I haven't been able to reproduce this (nor find any difference between the libretro and standalone builds)

I did discover another issue which might be related, though.  For 2 frames at the start of the battle, there was garbage at the top of the screen because CT enables both interlaced & overscan modes for a single scanline during those 2 frames (probably a game bug?)  That issue should be fixed as of the latest commit.

This does mean that the core turns on "high resolution" mode for those 2 frames, though - maybe the flashing/shifting you saw is the result of pixel shaders resulting in a different picture for the 2 frames where the resolution switches to 512x478?

**Comment by Awakened0** [comment]
Ahh right, I'm using crt-guest-dr-venom which has automatic deinterlacing when it detects high res content. Turning that shader off makes the flash go away. Or I can disable interlace detection in it's shader parameters. I can still see the res change for those two frames though, even with the latest commit. I wonder if supporting 512x239 mode will make it less noticeable since the scanlines wouldn't get squished. I don't see the change in snes9x or bsnes with that shader.

Anyways, looks like the specific game issue is fixed. Thanks!

**Comment by SourMesen** [comment]
The resolution change is normal. In this case, it's interlaced mode that gets turned on, not high resolution, so technically the resolution becomes 256x239i rather than the usual progressive res.  This makes it switch to 512x478, but I couldn't really make it 512x239 in this case, since it's interlaced rather than high res (like what was used in the other games).

I'm not too sure how bsnes/snes9x decide to keep the frame as non-interlaced, though.  Maybe they have some sort of threshold on the number of interlaced rows required? Or maybe the interlaced flag is only checked once per frame and switching it midway through the frame doesn't have any effect.  Some games definitely do switch between high res & non-high res mid-frame, but I'm not sure there's any game that switches to interlaced mode for part of the frame on purpose.
